aspyplugs_static:
  root_modules:
    aspynotifications_sdk:
      load_at_startup: []
      lazy_loaded:
      - name: notifications_client
        adapters:
        - type: NATS
          module: aspynotifications_sdk.adapters.notifications_nats_client
          eager: false
        - type: REST
          module: aspynotifications_sdk.adapters.notifications_rest_client
          eager: false
      user_decorators: []
