aspyplugs_static:
  root_modules:
    aspynotifications:
      load_at_startup: []
      lazy_loaded:
      - name: cloud_event_store
        adapters:
        - type: LOCALFS
          module: aspynotifications.adapters.cloud_event_file_adapter
          eager: false
        - type: MONGODB
          module: aspynotifications.adapters.cloud_event_mongo_adapter
          eager: false
      - name: destinations_store
        adapters:
        - type: LOCALFS
          module: aspynotifications.adapters.destinations_file_adapter
          eager: false
        - type: MONGODB
          module: aspynotifications.adapters.destinations_mongo_adapter
          eager: false
      - name: notification_policy_store
        adapters:
        - type: LOCALFS
          module: aspynotifications.adapters.policy_file_store
          eager: false
        - type: MONGODB
          module: aspynotifications.adapters.policy_mongo_store
          eager: false
      - name: notification_provider_store
        adapters:
        - type: LOCALFS
          module: aspynotifications.adapters.provider_file_store
          eager: false
        - type: MONGODB
          module: aspynotifications.adapters.provider_mongo_store
          eager: false
      - name: notification_sender
        adapters:
        - type: SLACK
          module: aspynotifications.adapters.notification_senders.slack_sender
          eager: false
        - type: ZEPTOMAIL
          module: aspynotifications.adapters.notification_senders.zeptomail_sender
          eager: false
      - name: template_store
        adapters:
        - type: LOCALFS
          module: aspynotifications.adapters.template_file_adapter
          eager: false
        - type: MONGODB
          module: aspynotifications.adapters.template_mongo_adapter
          eager: false
      user_decorators: []
