aspyevents_rest:
  deploy:
    templates:
    - src: aspyevents_rest.yaml.j2
      dest: '{{ install_dir }}/config/aspyevents_rest.yaml'
      permissions: '0600'
    - src: aspyevents_sdk.yaml.j2
      dest: '{{ install_dir }}/config/aspyevents_sdk.yaml'
      permissions: '0600'
    - src: aspytracing.yaml.j2
      dest: '{{ install_dir }}/config/aspytracing.yaml'
      permissions: '0600'
