aspynotifications_worker:
  deploy:
    templates:
    - src: aspynotifications.yaml.j2
      dest: '{{ install_dir }}/config/aspynotifications.yaml'
      permissions: '0600'
    - src: aspynotifications_worker.yaml.j2
      dest: '{{ install_dir }}/config/aspynotifications_worker.yaml'
      permissions: '0600'
    - src: aspytracing.yaml.j2
      dest: '{{ install_dir }}/config/aspytracing.yaml'
      permissions: '0600'
