aspyplugs_static:
  root_modules:
    aspynotifications_rest:
      load_at_startup: []
      lazy_loaded: []
      user_decorators:
      - name: asynccontextmanager
        module: aspynotifications_rest.api.main
        params: []
      - name: notification_administration_router
        module: aspynotifications_rest.api.notification_administration_handlers
        params: []
      - name: notification_administration_router
        module: aspynotifications_rest.api.notification_administration_handlers
        params: []
      - name: notification_administration_router
        module: aspynotifications_rest.api.notification_administration_handlers
        params: []
      - name: notification_administration_router
        module: aspynotifications_rest.api.notification_administration_handlers
        params: []
      - name: notification_administration_router
        module: aspynotifications_rest.api.notification_administration_handlers
        params: []
      - name: notification_administration_router
        module: aspynotifications_rest.api.notification_administration_handlers
        params: []
      - name: notification_administration_router
        module: aspynotifications_rest.api.notification_administration_handlers
        params: []
      - name: notification_administration_router
        module: aspynotifications_rest.api.notification_administration_handlers
        params: []
      - name: notification_administration_router
        module: aspynotifications_rest.api.notification_administration_handlers
        params: []
      - name: notification_administration_router
        module: aspynotifications_rest.api.notification_administration_handlers
        params: []
      - name: notifications_router
        module: aspynotifications_rest.api.notifications_handlers
        params: []
