aspyplugs_static:
  root_modules:
    aspynotifications_cli:
      load_at_startup: []
      lazy_loaded: []
      user_decorators:
      - name: common_logging_options
        module: aspynotifications_cli.cli.main
        params: []
