aspynotifications_rest:
  deploy:
    templates:
    - src: aspynotifications.yaml.j2
      dest: '{{ install_dir }}/config/aspynotifications.yaml'
      permissions: '0600'
    - src: aspynotifications_rest.yaml.j2
      dest: '{{ install_dir }}/config/aspynotifications_rest.yaml'
      permissions: '0600'
